services:
  mysql:
    build:
      context: .
      dockerfile: database.Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - datavolume:/var/lib/mysql



  yatv:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    links:
      - mysql:mysql
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: never
volumes:
  datavolume: